Enable multi tenancy
Onlineberatung/onlineBeratung-userService pull request #328
Opened 2022-03-23 07:31 UTC by mebo4b

## Provides tenant specific data separation/restriction 

- this feature can be activated with the new property "multitenancy.enabled" which defaults to false
- to use the whole feature there is a need to also setup the "TenantService"

2022-03-23 10:31 UTC, webatspeed requested changes

2022-03-23 10:31 UTC, webatspeed commented on src/main/java/de/caritas/cob/userservice/api/service/emailsupplier/TenantTemplateSupplier.java
> +  private TemplateDataDTO getTenantImpressumUrl(String tenantUrl) {
"Imprint"?

2022-03-23 10:31 UTC, webatspeed commented on src/main/java/de/caritas/cob/userservice/api/service/emailsupplier/TenantTemplateSupplier.java
> +  private TemplateDataDTO getTanantDatenschutzUrl(String tenantUrl) {
"Tenant", "Privacy"?

2022-03-23 10:31 UTC, webatspeed commented on src/main/resources/db/changelog/changeset/0019_tenant_id/tenant_id-rollback.sql
> +DROP `tenant_id`;
consultant_agency is missing

2022-03-23 10:31 UTC, webatspeed commented on src/test/java/de/caritas/cob/userservice/api/service/httpheader/TenantHeaderSupplierTest.java
> +class TenantHeaderSupplierTest {
Huh?

2022-03-23 10:31 UTC, webatspeed commented on src/test/resources/database/setTenantsSpecificData.sql
> +VALUES (101, '1', '0b3b1cc6-be98-4787-aa56-212259d811b7', 1);
Can we refrain from using static SQL inserts for tests and replace them with a programmatic setup? So, we notice model changes and do not have to maintain multiple locations if the model changes. You find an example of a programmatic approach in UserControllerE2EIT.givenAValidConsultantSpeaking as well as givenAnAgencyWithMultipleLanguages .

2022-03-23 10:31 UTC, webatspeed commented on src/test/resources/database/transformDataForTenants.sql
> +update SESSION set TENANT_ID = '2' where ID in (1,2);
Can we refrain from using static SQL inserts for tests and replace them with a programmatic setup? So, we notice model changes and do not have to maintain multiple locations if the model changes. You find an example of a programmatic approach in UserControllerE2EIT.restoreSession .

2022-03-23 10:31 UTC, webatspeed commented on src/main/java/de/caritas/cob/userservice/config/apiclient/TenantAdminServiceApiClient.java
> +package de.caritas.cob.userservice.config.apiclient;
package de.caritas.cob.userservice.api.config.apiclient; Same for the four other files.

2022-03-23 10:31 UTC, webatspeed commented on src/main/java/de/caritas/cob/userservice/filter/HttpTenantFilter.java
> +package de.caritas.cob.userservice.filter;
package de.caritas.cob.userservice.api.adapters.web.controller.interceptor.apiclient; ? Same for the two other files. We could replace the "interceptor" name if we only knew a good generic name for interceptor, filter, and advice.

2022-03-24 13:02 UTC, tkuzynow commented on src/main/java/de/caritas/cob/userservice/api/service/emailsupplier/TenantTemplateSupplier.java
> +  private TemplateDataDTO getTenantImpressumUrl(String tenantUrl) {
done

2022-03-24 13:02 UTC, tkuzynow commented on src/main/java/de/caritas/cob/userservice/api/service/emailsupplier/TenantTemplateSupplier.java
> +  private TemplateDataDTO getTanantDatenschutzUrl(String tenantUrl) {
done

2022-03-24 13:02 UTC, tkuzynow commented on src/main/resources/db/changelog/changeset/0019_tenant_id/tenant_id-rollback.sql
> +DROP `tenant_id`;
done

2022-03-24 13:02 UTC, tkuzynow commented on src/test/java/de/caritas/cob/userservice/api/service/httpheader/TenantHeaderSupplierTest.java
> +class TenantHeaderSupplierTest {
test restored and adapted

2022-03-24 14:05 UTC, tkuzynow commented on src/main/java/de/caritas/cob/userservice/config/apiclient/TenantAdminServiceApiClient.java
> +package de.caritas.cob.userservice.config.apiclient;
done

2022-03-24 14:42 UTC, tkuzynow commented on src/test/resources/database/setTenantsSpecificData.sql
> +VALUES (101, '1', '0b3b1cc6-be98-4787-aa56-212259d811b7', 1);
removed SQL and refactored other tests

2022-03-24 14:45 UTC, tkuzynow commented on src/test/resources/database/transformDataForTenants.sql
> +update SESSION set TENANT_ID = '2' where ID in (1,2);
I would skip this refactoring at this point of time, as it will add a lot of boilerplate code to update objects and cleanup the data after the test

2022-03-24 15:01 UTC, webatspeed approved these changes

2022-03-25 08:48 UTC, merged