Feat job delete obsolete appointments
Onlineberatung/onlineBeratung-userService pull request #348
Opened 2022-04-06 14:25 UTC by hill-daniel

2022-04-06 14:51 UTC, webatspeed commented
This branch is out-of-date with the base branch

2022-04-06 15:00 UTC, webatspeed requested changes

2022-04-06 15:00 UTC, webatspeed commented on src/main/java/de/caritas/cob/userservice/api/config/AppointmentConfig.java
> +  private int lifespanInHours;
You could benefit from quick validation by adding "@NotNull" and "@Positive". Also, the type should be Integer, so null does not convert to 0. Check the cron existence, too. If you change the key to "scheduler-cron" you can do it here.

2022-04-06 15:00 UTC, webatspeed commented on src/main/java/de/caritas/cob/userservice/api/config/AppointmentConfig.java
> +
From a former project, give it a try... 
```
	@NotBlank
	private String evictCron;

	@AssertTrue
	@SuppressWarnings("unused")
	private boolean isCronExpression() {
		try {
			CronExpression.parse(evictCron);
		} catch (IllegalArgumentException e) {
			return false;
		}

		return true;
	}
```

2022-04-06 15:00 UTC, webatspeed commented on src/main/java/de/caritas/cob/userservice/api/workflow/appointment/scheduler/DeleteObsoleteAppointmentsScheduler.java
> +  public void deleteObsoleteAppointments() {
Can this method be moved to the Organizer (if the Transactional annotation can be on method level)?

2022-04-06 15:54 UTC, hill-daniel commented on src/main/java/de/caritas/cob/userservice/api/workflow/appointment/scheduler/DeleteObsoleteAppointmentsScheduler.java
> +  public void deleteObsoleteAppointments() {
It can, but whats the reasoning behind? Why shouldn't the internal job have direct access to the repository?

2022-04-06 15:54 UTC, hill-daniel commented on src/main/java/de/caritas/cob/userservice/api/config/AppointmentConfig.java
> +
@scheduled(cron = "....") already checks for valid cron epxressions.

2022-04-07 10:52 UTC, webatspeed approved these changes

2022-04-07 10:57 UTC, merged