feat: set encryption on room information
Onlineberatung/onlineBeratung-userService pull request #401
Opened 2022-06-02 12:12 UTC by HannesKasstein

Disables encryption for group chats, when they're stopped.
Also disables encryption of repetitive group chats, when all standard users left.

2022-06-02 12:41 UTC, hill-daniel commented on src/main/java/de/caritas/cob/userservice/api/facade/JoinAndLeaveChatFacade.java
> +        rocketChatService.saveRoomSettings(chat.getGroupId(), false);
Is this already for the followup task?
Please check if "reset chat" means just setting encryption or if it means executing handleRepetitiveChatReset in the StopChatActionCommand.

2022-06-02 17:44 UTC, HannesKasstein commented on src/main/java/de/caritas/cob/userservice/api/facade/JoinAndLeaveChatFacade.java
> +        rocketChatService.saveRoomSettings(chat.getGroupId(), false);
Regarding the ticket, everything should be covered, but I'll consult @alxbenz again for clarification tomorrow.

2022-06-03 10:40 UTC, webatspeed requested changes

2022-06-03 10:40 UTC, webatspeed commented on .checkstyle
> +  <local-check-config name="maven-checkstyle-plugin validate" location="file:/Users/hanneskasstein/workspaces/virtual-identity.at/caritasdeutschland/caritas-onlineBeratung-userService/google_checks_l
We shouldn't add your local file path info to the repo. Can you ignore this file via gitignore, please?

2022-06-03 10:40 UTC, webatspeed commented on Dockerfile
> +COPY ./target/UserService.jar app.jar
This helps locally. Doesn't it hurt in github actions?

2022-06-03 10:40 UTC, webatspeed commented on src/main/java/de/caritas/cob/userservice/api/adapters/rocketchat/dto/room/RoomSettingsDTO.java
> +import lombok.AllArgsConstructor;
Please remove that fellow. It is not used. There is an Intellij setting for automatic removal.

2022-06-03 10:40 UTC, webatspeed commented on src/main/java/de/caritas/cob/userservice/api/adapters/rocketchat/RocketChatService.java
> +import de.caritas.cob.userservice.api.adapters.rocketchat.dto.user.RocketChatUserDTO;
Many doubled imports here.

2022-06-03 10:40 UTC, webatspeed commented on src/main/java/de/caritas/cob/userservice/api/adapters/rocketchat/RocketChatService.java
> +    var roomSettings = new RoomSettingsDTO(chatId, encrypted);
Can you use the mapper for such setups? Compare muteUserInChat.

2022-06-03 10:40 UTC, webatspeed commented on src/test/java/de/caritas/cob/userservice/api/adapters/web/controller/UserControllerE2EIT.java
> +  void saveRoomSettingsShouldReturnOkIfEncryptionIsDeactivated() throws Exception {
stopChatShould... because saveRoomSettings is not a UserController method and this is a UserController test class.

2022-06-03 10:40 UTC, webatspeed commented on src/test/java/de/caritas/cob/userservice/api/adapters/web/controller/UserControllerE2EIT.java
> +    verify(stopChatActionCommand).execute(chat);
Here should be checked if the call to RocketChat's saveRoomSettings endpoint has happened, as that is the other end of the end-to-end test. Compare updateE2eInChatsShouldRespondWithNoContentIfNotTemporarilyEncrypted, for instance.

2022-06-03 10:40 UTC, webatspeed commented on src/main/java/de/caritas/cob/userservice/api/facade/JoinAndLeaveChatFacade.java
> +      if (rocketChatService.getStandardMembersOfGroup(chat.getGroupId()).isEmpty()) {
How about adding a test for this new behaviour? Either in JoinAndLeaveChatFacadeTest or UserControllerE2EIT.

2022-06-03 10:40 UTC, HannesKasstein commented on src/main/java/de/caritas/cob/userservice/api/facade/JoinAndLeaveChatFacade.java
> +        rocketChatService.saveRoomSettings(chat.getGroupId(), false);
After talking to @alxbenz it's not necessary to delete the old messages. We can keep them for now, although they won't be readable anymore. Import is, that the encryption will be reset and that's implemented now.

2022-06-08 10:22 UTC, HannesKasstein commented on src/test/java/de/caritas/cob/userservice/api/adapters/web/controller/UserControllerE2EIT.java
> +    verify(stopChatActionCommand).execute(chat);
It's already covered by stopChat_should_set_encrypted_room_settings_to_false() in StopChatActionCommandTest
Should I change that or is that enough?

2022-06-08 10:56 UTC, webatspeed commented on src/test/java/de/caritas/cob/userservice/api/adapters/web/controller/UserControllerE2EIT.java
> +    verify(stopChatActionCommand).execute(chat);
all right

2022-06-08 12:50 UTC, HannesKasstein commented on src/main/java/de/caritas/cob/userservice/api/facade/JoinAndLeaveChatFacade.java
> +      if (rocketChatService.getStandardMembersOfGroup(chat.getGroupId()).isEmpty()) {
I added the missing test in the JoinAndLeaveChatFacadeTest class

2022-06-08 14:12 UTC, webatspeed approved these changes

2022-06-08 14:26 UTC, merged