Feature delete recreate empty chats
Onlineberatung/onlineBeratung-userService pull request #413
Opened 2022-06-12 11:03 UTC by webatspeed

2022-06-13 06:51 UTC, hill-daniel requested changes

2022-06-13 06:51 UTC, hill-daniel commented on src/main/java/de/caritas/cob/userservice/api/actions/chat/StopChatActionCommand.java
> +public class StopChatActionCommand extends RecreateChatCapability implements ActionCommand<Chat> {
Just curious, why did you go for inheritance instead of a component here?
I'd favor composition over inheritance.

2022-06-13 06:51 UTC, hill-daniel commented on src/main/java/de/caritas/cob/userservice/api/actions/chat/RecreateChatCapability.java
> +  protected ChatPermissionVerifier chatPermissionVerifier;
ChatPermissionVerifier only is used in JoinAndLeaveChatFacade and in the other subclass (StopChatActionCommand) it is null. Maybe the verifier should be moved to this class.

2022-06-13 06:51 UTC, hill-daniel commented on src/main/java/de/caritas/cob/userservice/api/actions/chat/RecreateChatCapability.java
> +  protected ConsultantService consultantService;
Same with ConsultantService (see above)

2022-06-13 06:51 UTC, hill-daniel commented on src/main/java/de/caritas/cob/userservice/api/actions/chat/RecreateChatCapability.java
> +  protected UserService userService;
Same with UserService (see above)

2022-06-14 07:38 UTC, webatspeed commented on src/main/java/de/caritas/cob/userservice/api/actions/chat/RecreateChatCapability.java
> +  protected ChatPermissionVerifier chatPermissionVerifier;
Right, I moved it.

2022-06-14 07:38 UTC, webatspeed commented on src/main/java/de/caritas/cob/userservice/api/actions/chat/RecreateChatCapability.java
> +  protected ConsultantService consultantService;
Moved, too.

2022-06-14 07:38 UTC, webatspeed commented on src/main/java/de/caritas/cob/userservice/api/actions/chat/RecreateChatCapability.java
> +  protected UserService userService;
Moved again.

2022-06-14 07:54 UTC, webatspeed commented on src/main/java/de/caritas/cob/userservice/api/actions/chat/StopChatActionCommand.java
> +public class StopChatActionCommand extends RecreateChatCapability implements ActionCommand<Chat> {
That has a bit of a history: I intentionally tried to duplicate the code to ease the future development. The places in which recreation is used should be in exactly one place anyway. But changing that would have meant a larger refactoring and there is no time. Sonar intervened, so I tried to suppress the duplication error, but failed (see commits.) Then I went for the subclass approach to maximise the re-use of the existing unit tests. Anyway, I am going to change it into a Component and have to put increased effort into the unit tests that discourage the diamond testing approach in favour of the old-school pyramid one.

2022-06-15 11:04 UTC, hill-daniel approved these changes

2022-06-15 11:05 UTC, merged