Feat/vic 1343 registration statistics
Onlineberatung/onlineBeratung-userService pull request #483
Opened 2022-09-07 09:12 UTC by PhilippFr

Fixes #

## Proposed Changes

  -
  -
  -

2022-09-15 10:33 UTC, tkuzynow commented on src/main/java/de/caritas/cob/userservice/api/facade/CreateUserFacade.java
> +  private final @NonNull RegistrationStatisticsHelper registrationStatisticsHelper;
Please avoid class names like Helper as this is not compliant with clean code

2022-09-15 10:39 UTC, tkuzynow commented on src/main/java/de/caritas/cob/userservice/api/service/consultingtype/TopicService.java
> +    return createTopicControllerApiWithoutHeaders().getAllActiveTopics();
In this case I see the point of having a variable named var topicControllerPublicAPI = createTopicControllerApiWithoutHeaders()

a small thing: I also suggest to use API instead of Api in the method name.

2022-09-15 10:44 UTC, tkuzynow commented on src/test/java/de/caritas/cob/userservice/api/testHelper/TestConstants.java
> +  public static final Long TENANT_ID = 1L;
do we really need to put it to TestConstants? We should be careful, as it's can easily create additional dependencies between tests, that we don't need or want.

2022-09-15 10:46 UTC, tkuzynow requested changes
the code is okay, found only couple of small naming things that should be amended.

2022-09-15 13:50 UTC, PhilippFr commented on src/main/java/de/caritas/cob/userservice/api/facade/CreateUserFacade.java
> +  private final @NonNull RegistrationStatisticsHelper registrationStatisticsHelper;
Moved to topicService Class

2022-09-15 13:54 UTC, PhilippFr commented on src/main/java/de/caritas/cob/userservice/api/service/consultingtype/TopicService.java
> +    return createTopicControllerApiWithoutHeaders().getAllActiveTopics();
I think I usually got with "Api" since all uppercase is against many style formats and will trigger linters.

2022-09-15 13:56 UTC, PhilippFr commented on src/test/java/de/caritas/cob/userservice/api/testHelper/TestConstants.java
> +  public static final Long TENANT_ID = 1L;
TestConstants is being used for this purpose across most tests in most services, so im just sticking to the pattern i guess. Not sure how this would cause dependency issues?

2022-09-16 10:51 UTC, tkuzynow commented on src/test/java/de/caritas/cob/userservice/api/testHelper/TestConstants.java
> +  public static final Long TENANT_ID = 1L;
I understand your point, however common TestConstants introduces dependency between tests, as if you need to change it for one test, it may break others

2022-09-16 12:19 UTC, tkuzynow approved these changes

2022-09-16 12:19 UTC, merged